# Generated by Django 3.0.5 on 2020-10-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorturl',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
                ('ori_url', models.CharField(max_length=500)),
                ('short_url', models.CharField(max_length=500)),
            ],
        ),
    ]
