# Generated by Django 3.0.5 on 2020-10-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='uni_key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
